openapi: "3.0.3"
info:
  title: "sdkman_state API"
  description: "sdkman_state API"
  version: "1.0.0"
servers:
- url: "https://sdkman_state"
paths:
  /versions:
    delete:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/UniqueVersion"
        required: true
      responses:
        "204":
          description: "No Content"
          content:
            '*/*':
              schema:
                type: "object"
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/Version"
        required: true
      responses:
        "204":
          description: "No Content"
          content:
            '*/*':
              schema:
                type: "object"
  /versions/{candidate}:
    get:
      description: ""
      parameters:
      - name: "candidate"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Version"
components:
  schemas:
    UniqueVersion:
      type: "object"
      properties:
        candidate:
          type: "string"
        version:
          type: "string"
        vendor:
          type: "string"
        platform:
          type: "string"
      required:
      - "candidate"
      - "version"
      - "vendor"
      - "platform"
    Version:
      type: "object"
      properties:
        candidate:
          type: "string"
        version:
          type: "string"
        vendor:
          type: "string"
        platform:
          type: "string"
        url:
          type: "string"
        visible:
          type: "boolean"
        md5sum:
          type: "string"
        sha256sum:
          type: "string"
        sha512sum:
          type: "string"
      required:
      - "candidate"
      - "version"
      - "vendor"
      - "platform"
      - "url"